site_name: "Portfolio"
site_author: "Badma Gakhaev"

theme:
  name: material
  language: en
  # Добавляем логотип (иконку книги) в шапку
  icon:
    logo: material/book-open-page-variant
  # Настраиваем палитру и переключатель темной/светлой темы
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Включить темную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Включить светлую тему
  features:
    - navigation.instant # Верхнее меню
    - content.code.copy # Кнопка копирования кода
  

repo_name: badmuchi/Tech-writer
repo_url: https://github.com/badmuchi/Tech-writer

# Добавляем социальные кнопки в футер (подвал) сайта
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/badmuchi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/badma-gakhaev-913a7438/  # Замени на свой, если есть
  alternate:
    - name: English (EN)
      link: /Tech-writer/CV/
      lang: en
    - name: Русский (RU)
      link: /Tech-writer/CV-Ru/
      lang: ru
nav:
  - Home: index.md
  - Weather API Guide: api-guide.md
  - API Spec: api-spec.md
  - API Errors: api-errors.md
  - CV (En): cv.md
  - CV (Ru): cv-ru.md

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences # Корректное отображение блоков кода